# Generated by Django 4.2 on 2023-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers_friendship_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_participants',
            name='modelator',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=5, max_length=256),
            preserve_default=False,
        ),
    ]
