# Generated by Django 4.2 on 2023-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_lang_delete_country_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='available_lang',
            field=models.ManyToManyField(to='api.language'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='api.genre'),
        ),
    ]
